name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'  # Use the version of .NET you are targeting

    - name: Build Blazor WebAssembly App
      run: |
        cd BlazorAppStaticWeb/IdeaStudio.Website
        dotnet publish -c Release -o wwwroot

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WATER_0E1C1E703 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: 'BlazorAppStaticWeb/IdeaStudio.Website'  # Path to your Blazor project
        api_location: ''  # Change this to the path of your API project if you have one
        output_location: 'wwwroot'  # This is where the Blazor WebAssembly files are published